# Generated by Django 5.0.6 on 2024-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageserv',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='imageserv',
            name='idImage',
        ),
        migrations.RemoveField(
            model_name='imageserv',
            name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='imageserv',
            name='slug',
        ),
        migrations.AlterField(
            model_name='imageserv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/serviceImages'),
        ),
    ]
