# Generated by Django 5.0.6 on 2024-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0002_remove_imageserv_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserv',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageserv',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
