# Generated by Django 5.0.6 on 2024-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0005_rename_body_post_description_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
