# Generated by Django 5.0.6 on 2024-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0007_remove_post_image_remove_postimage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
