# Generated by Django 5.0.6 on 2024-07-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0010_remove_postimage_image_post_image_postimage_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default=1, upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logAuth.post'),
        ),
    ]
