# Generated by Django 5.0.6 on 2024-07-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0012_rename_content_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
