# Generated by Django 5.0.6 on 2024-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(default=1, upload_to='thumbnail/'),
            preserve_default=False,
        ),
    ]
