# Generated by Django 5.0.6 on 2024-07-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0014_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
