# Generated by Django 5.0.6 on 2024-07-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0016_rename_images_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
