# Generated by Django 5.0.6 on 2024-08-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0017_remove_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittleLogo', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/logoImage')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
