# Generated by Django 5.0.6 on 2024-08-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0018_logoimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logoimg',
            old_name='tittleLogo',
            new_name='titleLogo',
        ),
    ]
