# Generated by Django 5.0.6 on 2024-07-12 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(blank=True, max_length=200, null=True)),
                ('contactEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPhone', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNote', models.TextField(blank=True, null=True)),
                ('idContact', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
